name: Build & Push Docker Images

on: 
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Set Docker image prefix
              run: |
                echo "DOCKER_IMAGE_PREFIX=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            #------------ Backend -------------
            - name: Build Backend image
              run: |
                docker build -t ghcr.io/${{ env.DOCKER_IMAGE_PREFIX }}-backend:latest ./backend
                
            - name: Push Backend image
              run: |
                docker push ghcr.io/${{ env.DOCKER_IMAGE_PREFIX }}-backend:latest

            #----------- Frontend  ----------
            - name: Copy proto files to frontend
              run: mkdir -p frontend/public/proto && cp backend/src/proto/user.proto frontend/public/proto/

            - name: Build Frontend image
              run: docker build -t ghcr.io/${{ env.DOCKER_IMAGE_PREFIX }}-frontend:latest ./frontend

            - name: Push frontend Image
              run: |
                docker push ghcr.io/${{ env.DOCKER_IMAGE_PREFIX }}-frontend:latest

              

